project:
  type: website

website:
  title: "Akshaya's Visual Analytics Page"
  navbar:
    left: 
    - text: "Hands-on Exercises"
      menu: 
      - text: "Hands-on Exercise 1"
        href: "HE01.html"
      - text: "Hands-on Exercise 2"
        href: "HE02.html"
      - text: "Hands-on Exercise 3-A"
        href: "HE03.1.html"
      - text: "Hands-on Exercise 3-B"
        href: "HE03.2.html"
      - text: "Hands-on Exercise 4"
        href: "HE04.html"
      - text: "Hands-on Exercise 5"
        href: "HE05.html"
    - text: "In-class Exercises"
      href: "https://public.tableau.com/app/profile/akshaya.v.s/vizzes"
    - text: "Take-home Exercises"
      menu: 
      - text: "Take-home Exercise 1"
        href: "TE01.html"
      - text: "Take-home Exercise 2"
        href: "TE02.html"
    - text: "Project"
    right:
      - href: index.qmd
        text: Home
      - about.qmd


format:
  html:
    theme:
      - minty
    toc: true
    toc-title: "On this page"
    page-layout: full
    smooth-scroll: true
    number-sections: true
    

editor: visual

