project:
  type: website

website:
  title: "Akshaya's Visual Analytics Page"
  navbar:
    left: 
    - text: "Hands-on Exercises"
      menu: 
      - text: "Hands-on Exercise 1"
        href: "HE01.html"
      - text: "Hands-on Exercise 2"
        href: "HE02.html"
      - text: "Hands-on Exercise 3-A"
        href: "HE03.1.html"
      - text: "Hands-on Exercise 3-B"
        href: "HE03.2.html"
      - text: "Hands-on Exercise 4-A"
        href: "HE04.1.html"
      - text: "Hands-on Exercise 4-B"
        href: "HE04.2.html"
      - text: "Hands-on Exercise 4-C"
        href: "HE04.3.html"
      - text: "Hands-on Exercise 4-D"
        href: "HE04.4.html"
      - text: "Hands-on Exercise 5-A"
        href: "HE05.1.html"
      - text: "Hands-on Exercise 5-B"
        href: "HE05.2.html"  
      - text: "Hands-on Exercise 5-C"
        href: "HE05.3.html"
      - text: "Hands-on Exercise 5-D"
        href: "HE05.4.html"
      - text: "Hands-on Exercise 5-E"
        href: "HE05.5.html"
      - text: "Hands-on Exercise 6"
        href: "HE06.html"    
      - text: "Hands-on Exercise 7-A"
        href: "HE07.1.html"  
      - text: "Hands-on Exercise 7-B"
        href: "HE07.2.html" 
      - text: "Hands-on Exercise 7-C"
        href: "HE07.3.html"  
    - text: "In-class Exercises"
      href: "https://public.tableau.com/app/profile/akshaya.v.s/vizzes"
    - text: "Take-home Exercises"
      menu: 
      - text: "Take-home Exercise 1"
        href: "TE01.html"
    - text: "Project"
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - flatly
    page-layout: full
    toc: true
    toc-title: "On this page"
    smooth-scroll: true
    number-sections: true

editor: visual

